import '../models/playlist.dart';
import '../models/track.dart';

/// Provides curated built-in playlists that are immediately playable,
/// featuring rich covers and instant streaming via YouTube IFrame Player.
class BuiltinPlaylistsService {
  static final List<Playlist> _builtinPlaylists = [
    // 1. Featured Daily Mix: After Dark
    Playlist(
      id: 'builtin_after_dark',
      name: 'After Dark',
      description: 'Electronic focus & synthwave for late nights',
      createdAt: DateTime(2024, 1, 1),
      updatedAt: DateTime.now(),
      tracks: [
        const Track(
          id: 'yt_waAlgFq9Xq8',
          title: 'After Dark',
          artist: 'Mr.Kitty',
          artworkUrl150: 'https://img.youtube.com/vi/waAlgFq9Xq8/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/waAlgFq9Xq8/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/waAlgFq9Xq8/hqdefault.jpg',
          durationSeconds: 259,
          genre: 'Electronic',
          provider: 'youtube',
          youtubeVideoId: 'waAlgFq9Xq8',
        ),
        const Track(
          id: 'yt_8GW6sLrK40k',
          title: 'Resonance',
          artist: 'HOME',
          artworkUrl150: 'https://img.youtube.com/vi/8GW6sLrK40k/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/8GW6sLrK40k/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/8GW6sLrK40k/hqdefault.jpg',
          durationSeconds: 212,
          genre: 'Electronic',
          provider: 'youtube',
          youtubeVideoId: '8GW6sLrK40k',
        ),
        const Track(
          id: 'yt_MV_3Dpw-BRY',
          title: 'Nightcall',
          artist: 'Kavinsky',
          artworkUrl150: 'https://img.youtube.com/vi/MV_3Dpw-BRY/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/MV_3Dpw-BRY/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/MV_3Dpw-BRY/hqdefault.jpg',
          durationSeconds: 259,
          genre: 'Electronic',
          provider: 'youtube',
          youtubeVideoId: 'MV_3Dpw-BRY',
        ),
        const Track(
          id: 'yt_34Na4j8AVgA',
          title: 'Starboy',
          artist: 'The Weeknd ft. Daft Punk',
          artworkUrl150: 'https://img.youtube.com/vi/34Na4j8AVgA/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/34Na4j8AVgA/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/34Na4j8AVgA/hqdefault.jpg',
          durationSeconds: 230,
          genre: 'Electronic',
          provider: 'youtube',
          youtubeVideoId: '34Na4j8AVgA',
        ),
      ],
    ),

    // 2. Global Pop Essentials (featuring Adele, Taylor Swift, The Weeknd)
    Playlist(
      id: 'builtin_global_pop',
      name: 'Global Pop Essentials',
      description: 'The world\'s biggest hits & timeless vocal anthems',
      createdAt: DateTime(2024, 1, 1),
      updatedAt: DateTime.now(),
      tracks: [
        const Track(
          id: 'yt_0wPhbmeNSOs',
          title: 'Lovesong',
          artist: 'Adele',
          artworkUrl150: 'https://img.youtube.com/vi/0wPhbmeNSOs/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/0wPhbmeNSOs/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/0wPhbmeNSOs/hqdefault.jpg',
          durationSeconds: 320,
          genre: 'Pop',
          provider: 'youtube',
          youtubeVideoId: '0wPhbmeNSOs',
        ),
        const Track(
          id: 'yt_U3ASj1L6_sY',
          title: 'Easy On Me',
          artist: 'Adele',
          artworkUrl150: 'https://img.youtube.com/vi/U3ASj1L6_sY/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/U3ASj1L6_sY/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/U3ASj1L6_sY/hqdefault.jpg',
          durationSeconds: 224,
          genre: 'Pop',
          provider: 'youtube',
          youtubeVideoId: 'U3ASj1L6_sY',
        ),
        const Track(
          id: 'yt_4NRXx6U8ABQ',
          title: 'Blinding Lights',
          artist: 'The Weeknd',
          artworkUrl150: 'https://img.youtube.com/vi/4NRXx6U8ABQ/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/4NRXx6U8ABQ/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/4NRXx6U8ABQ/hqdefault.jpg',
          durationSeconds: 200,
          genre: 'Pop',
          provider: 'youtube',
          youtubeVideoId: '4NRXx6U8ABQ',
        ),
        const Track(
          id: 'yt_ic8j13piAhQ',
          title: 'Cruel Summer',
          artist: 'Taylor Swift',
          artworkUrl150: 'https://img.youtube.com/vi/ic8j13piAhQ/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/ic8j13piAhQ/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/ic8j13piAhQ/hqdefault.jpg',
          durationSeconds: 178,
          genre: 'Pop',
          provider: 'youtube',
          youtubeVideoId: 'ic8j13piAhQ',
        ),
      ],
    ),

    // 3. Bollywood Essentials
    Playlist(
      id: 'builtin_bollywood',
      name: 'Bollywood Top Hits',
      description: 'Soulful melodies and romantic chartbusters',
      createdAt: DateTime(2024, 1, 1),
      updatedAt: DateTime.now(),
      tracks: [
        const Track(
          id: 'yt_BddP6PYo2gs',
          title: 'Kesariya',
          artist: 'Arijit Singh, Pritam',
          artworkUrl150: 'https://img.youtube.com/vi/BddP6PYo2gs/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/BddP6PYo2gs/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/BddP6PYo2gs/hqdefault.jpg',
          durationSeconds: 268,
          genre: 'Bollywood',
          provider: 'youtube',
          youtubeVideoId: 'BddP6PYo2gs',
        ),
        const Track(
          id: 'yt_IJq0yyWug1k',
          title: 'Tum Hi Ho',
          artist: 'Arijit Singh, Mithoon',
          artworkUrl150: 'https://img.youtube.com/vi/IJq0yyWug1k/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/IJq0yyWug1k/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/IJq0yyWug1k/hqdefault.jpg',
          durationSeconds: 262,
          genre: 'Bollywood',
          provider: 'youtube',
          youtubeVideoId: 'IJq0yyWug1k',
        ),
        const Track(
          id: 'yt_V1Z5W5k9P7g',
          title: 'Chaleya',
          artist: 'Arijit Singh, Shilpa Rao',
          artworkUrl150: 'https://img.youtube.com/vi/V1Z5W5k9P7g/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/V1Z5W5k9P7g/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/V1Z5W5k9P7g/hqdefault.jpg',
          durationSeconds: 200,
          genre: 'Bollywood',
          provider: 'youtube',
          youtubeVideoId: 'V1Z5W5k9P7g',
        ),
      ],
    ),

    // 4. Focus Flow
    Playlist(
      id: 'builtin_focus_flow',
      name: 'Focus Flow',
      description: 'Pulse playlist · Deep study beats & ambient relaxation',
      createdAt: DateTime(2024, 1, 1),
      updatedAt: DateTime.now(),
      tracks: [
        const Track(
          id: 'yt_jfKfPfyJRdk',
          title: 'Lofi Hip Hop Chill Study Beat',
          artist: 'Lofi Girl',
          artworkUrl150: 'https://img.youtube.com/vi/jfKfPfyJRdk/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/jfKfPfyJRdk/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/jfKfPfyJRdk/hqdefault.jpg',
          durationSeconds: 180,
          genre: 'Focus',
          provider: 'youtube',
          youtubeVideoId: 'jfKfPfyJRdk',
        ),
        const Track(
          id: 'yt_2atQnvunGCo',
          title: 'Weightless',
          artist: 'Marconi Union',
          artworkUrl150: 'https://img.youtube.com/vi/2atQnvunGCo/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/2atQnvunGCo/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/2atQnvunGCo/hqdefault.jpg',
          durationSeconds: 485,
          genre: 'Focus',
          provider: 'youtube',
          youtubeVideoId: '2atQnvunGCo',
        ),
      ],
    ),
    // 5. India's Biggest Hits Playlists (matching YouTube Music shelf)
    Playlist(
      id: 'builtin_hits_2026',
      name: 'HITS OF 2026 SO FAR',
      description: 'The defining global and Indian chartbusters of the year',
      createdAt: DateTime(2026, 1, 1),
      updatedAt: DateTime.now(),
      tracks: [
        const Track(
          id: 'yt_D-YDEusVhWw',
          title: 'love nwantiti (ah ah ah)',
          artist: 'CKay',
          album: 'CKay The First',
          artworkUrl150: 'https://img.youtube.com/vi/D-YDEusVhWw/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/D-YDEusVhWw/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/D-YDEusVhWw/hqdefault.jpg',
          durationSeconds: 146,
          explicit: true,
          genre: 'Afrobeats',
          provider: 'youtube',
          youtubeVideoId: 'D-YDEusVhWw',
        ),
        const Track(
          id: 'yt_nyuo9-OjNNg',
          title: 'I Wanna Be Yours',
          artist: 'Arctic Monkeys',
          album: 'AM',
          artworkUrl150: 'https://img.youtube.com/vi/nyuo9-OjNNg/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/nyuo9-OjNNg/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/nyuo9-OjNNg/hqdefault.jpg',
          durationSeconds: 184,
          genre: 'Rock',
          provider: 'youtube',
          youtubeVideoId: 'nyuo9-OjNNg',
        ),
      ],
    ),
    Playlist(
      id: 'builtin_arijit_hits',
      name: 'Arijit Singh Hits',
      description: 'The definitive collection of soulful melodies by Arijit Singh',
      createdAt: DateTime(2024, 1, 1),
      updatedAt: DateTime.now(),
      tracks: [
        const Track(
          id: 'yt_4rGZk_FvYqQ',
          title: 'Phir Mohabbat',
          artist: 'Arijit Singh',
          album: 'Murder 2',
          artworkUrl150: 'https://img.youtube.com/vi/4rGZk_FvYqQ/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/4rGZk_FvYqQ/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/4rGZk_FvYqQ/hqdefault.jpg',
          durationSeconds: 330,
          genre: 'Bollywood',
          provider: 'youtube',
          youtubeVideoId: '4rGZk_FvYqQ',
        ),
        const Track(
          id: 'yt_BddP6PYo2gs',
          title: 'Kesariya',
          artist: 'Arijit Singh, Pritam',
          album: 'Brahmastra',
          artworkUrl150: 'https://img.youtube.com/vi/BddP6PYo2gs/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/BddP6PYo2gs/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/BddP6PYo2gs/hqdefault.jpg',
          durationSeconds: 268,
          genre: 'Bollywood',
          provider: 'youtube',
          youtubeVideoId: 'BddP6PYo2gs',
        ),
      ],
    ),
    Playlist(
      id: 'builtin_punjab_fire',
      name: 'PUNJAB DA FIRE',
      description: 'High energy Punjabi beats, hip hop and chartbusters',
      createdAt: DateTime(2024, 1, 1),
      updatedAt: DateTime.now(),
      tracks: [
        const Track(
          id: 'yt_rF8qOcvK64c',
          title: 'Pal Pal (with Talwiinder)',
          artist: 'Afusic, Talwiinder',
          album: 'Pal Pal',
          artworkUrl150: 'https://img.youtube.com/vi/rF8qOcvK64c/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/rF8qOcvK64c/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/rF8qOcvK64c/hqdefault.jpg',
          durationSeconds: 195,
          genre: 'Punjabi',
          provider: 'youtube',
          youtubeVideoId: 'rF8qOcvK64c',
        ),
        const Track(
          id: 'yt_61N6K8Yc3Wc',
          title: 'Khat',
          artist: 'Navjot Ahuja',
          album: 'Khat',
          artworkUrl150: 'https://img.youtube.com/vi/61N6K8Yc3Wc/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/61N6K8Yc3Wc/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/61N6K8Yc3Wc/hqdefault.jpg',
          durationSeconds: 182,
          genre: 'Punjabi',
          provider: 'youtube',
          youtubeVideoId: '61N6K8Yc3Wc',
        ),
      ],
    ),
    Playlist(
      id: 'builtin_ipop_hits',
      name: 'I-POP HITS',
      description: 'The trendiest non-film Indian Pop and independent anthems',
      createdAt: DateTime(2024, 1, 1),
      updatedAt: DateTime.now(),
      tracks: [
        const Track(
          id: 'yt_jTjSvhN4M24',
          title: 'Sahiba',
          artist: 'Aditya Rikhari',
          album: 'Sahiba',
          artworkUrl150: 'https://img.youtube.com/vi/jTjSvhN4M24/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/jTjSvhN4M24/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/jTjSvhN4M24/hqdefault.jpg',
          durationSeconds: 175,
          genre: 'Indie',
          provider: 'youtube',
          youtubeVideoId: 'jTjSvhN4M24',
        ),
        const Track(
          id: 'yt_sWdPhP2nL3w',
          title: 'Jhol',
          artist: 'Maanu & Annural Khalid',
          album: 'Jhol',
          artworkUrl150: 'https://img.youtube.com/vi/sWdPhP2nL3w/default.jpg',
          artworkUrl480: 'https://img.youtube.com/vi/sWdPhP2nL3w/mqdefault.jpg',
          artworkUrl1000: 'https://img.youtube.com/vi/sWdPhP2nL3w/hqdefault.jpg',
          durationSeconds: 210,
          genre: 'Indie',
          provider: 'youtube',
          youtubeVideoId: 'sWdPhP2nL3w',
        ),
      ],
    ),
  ];

  /// Curated quick picks matching the YouTube Music desktop home feed.
  static final List<Track> curatedQuickPicks = [
    const Track(
      id: 'yt_D-YDEusVhWw',
      title: 'love nwantiti (ah ah ah)',
      artist: 'CKay',
      album: 'CKay The First',
      artworkUrl150: 'https://img.youtube.com/vi/D-YDEusVhWw/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/D-YDEusVhWw/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/D-YDEusVhWw/hqdefault.jpg',
      durationSeconds: 146,
      explicit: true,
      genre: 'Afrobeats',
      provider: 'youtube',
      youtubeVideoId: 'D-YDEusVhWw',
    ),
    const Track(
      id: 'yt_nyuo9-OjNNg',
      title: 'I Wanna Be Yours',
      artist: 'Arctic Monkeys',
      album: 'AM',
      artworkUrl150: 'https://img.youtube.com/vi/nyuo9-OjNNg/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/nyuo9-OjNNg/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/nyuo9-OjNNg/hqdefault.jpg',
      durationSeconds: 184,
      genre: 'Rock',
      provider: 'youtube',
      youtubeVideoId: 'nyuo9-OjNNg',
    ),
    const Track(
      id: 'yt_ApXoWvfEYVU',
      title: 'Sunflower (Remix)',
      artist: 'Post Malone, Swae Lee',
      album: 'Spider-Man: Into the Spider-Verse',
      artworkUrl150: 'https://img.youtube.com/vi/ApXoWvfEYVU/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/ApXoWvfEYVU/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/ApXoWvfEYVU/hqdefault.jpg',
      durationSeconds: 158,
      genre: 'Hip-Hop',
      provider: 'youtube',
      youtubeVideoId: 'ApXoWvfEYVU',
    ),
    const Track(
      id: 'yt_6M_tHqW3wX8',
      title: 'KALYANI (Remix)',
      artist: 'ARJN, KDS, FIFTY',
      album: 'KALYANI (Remix)',
      artworkUrl150: 'https://img.youtube.com/vi/6M_tHqW3wX8/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/6M_tHqW3wX8/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/6M_tHqW3wX8/hqdefault.jpg',
      durationSeconds: 170,
      genre: 'Electronic',
      provider: 'youtube',
      youtubeVideoId: '6M_tHqW3wX8',
    ),
    const Track(
      id: 'yt_7C_wZ47pWyg',
      title: 'Bairan',
      artist: 'Banjaare',
      album: 'Bairan',
      artworkUrl150: 'https://img.youtube.com/vi/7C_wZ47pWyg/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/7C_wZ47pWyg/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/7C_wZ47pWyg/hqdefault.jpg',
      durationSeconds: 215,
      genre: 'Indian Pop',
      provider: 'youtube',
      youtubeVideoId: '7C_wZ47pWyg',
    ),
    const Track(
      id: 'yt_rF8qOcvK64c',
      title: 'Pal Pal (with Talwiinder)',
      artist: 'Afusic, Talwiinder',
      album: 'Pal Pal',
      artworkUrl150: 'https://img.youtube.com/vi/rF8qOcvK64c/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/rF8qOcvK64c/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/rF8qOcvK64c/hqdefault.jpg',
      durationSeconds: 195,
      genre: 'Punjabi',
      provider: 'youtube',
      youtubeVideoId: 'rF8qOcvK64c',
    ),
    const Track(
      id: 'yt_sWdPhP2nL3w',
      title: 'Jhol',
      artist: 'Maanu & Annural Khalid',
      album: 'Jhol',
      artworkUrl150: 'https://img.youtube.com/vi/sWdPhP2nL3w/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/sWdPhP2nL3w/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/sWdPhP2nL3w/hqdefault.jpg',
      durationSeconds: 210,
      genre: 'Indie',
      provider: 'youtube',
      youtubeVideoId: 'sWdPhP2nL3w',
    ),
    const Track(
      id: 'yt_Q8n5S0U0dZg',
      title: 'Jaan Se Guzarte Hain (Remix / Disco)',
      artist: 'Nusrat Fateh Ali Khan',
      album: 'Jaan Se Guzarte Hain',
      artworkUrl150: 'https://img.youtube.com/vi/Q8n5S0U0dZg/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/Q8n5S0U0dZg/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/Q8n5S0U0dZg/hqdefault.jpg',
      durationSeconds: 240,
      genre: 'Qawwali',
      provider: 'youtube',
      youtubeVideoId: 'Q8n5S0U0dZg',
    ),
    const Track(
      id: 'yt_4rGZk_FvYqQ',
      title: 'Phir Mohabbat',
      artist: 'Arijit Singh',
      album: 'Murder 2',
      artworkUrl150: 'https://img.youtube.com/vi/4rGZk_FvYqQ/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/4rGZk_FvYqQ/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/4rGZk_FvYqQ/hqdefault.jpg',
      durationSeconds: 330,
      genre: 'Bollywood',
      provider: 'youtube',
      youtubeVideoId: '4rGZk_FvYqQ',
    ),
    const Track(
      id: 'yt_61N6K8Yc3Wc',
      title: 'Khat',
      artist: 'Navjot Ahuja',
      album: 'Khat',
      artworkUrl150: 'https://img.youtube.com/vi/61N6K8Yc3Wc/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/61N6K8Yc3Wc/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/61N6K8Yc3Wc/hqdefault.jpg',
      durationSeconds: 182,
      genre: 'Punjabi',
      provider: 'youtube',
      youtubeVideoId: '61N6K8Yc3Wc',
    ),
    const Track(
      id: 'yt_jTjSvhN4M24',
      title: 'Sahiba',
      artist: 'Aditya Rikhari',
      album: 'Sahiba',
      artworkUrl150: 'https://img.youtube.com/vi/jTjSvhN4M24/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/jTjSvhN4M24/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/jTjSvhN4M24/hqdefault.jpg',
      durationSeconds: 175,
      genre: 'Indie',
      provider: 'youtube',
      youtubeVideoId: 'jTjSvhN4M24',
    ),
    const Track(
      id: 'yt__u_p_e68M8I',
      title: 'AKHIYAAAN',
      artist: 'Mudasir Hassan',
      album: 'AKHIYAAAN',
      artworkUrl150: 'https://img.youtube.com/vi/_u_p_e68M8I/default.jpg',
      artworkUrl480: 'https://img.youtube.com/vi/_u_p_e68M8I/mqdefault.jpg',
      artworkUrl1000: 'https://img.youtube.com/vi/_u_p_e68M8I/hqdefault.jpg',
      durationSeconds: 198,
      genre: 'Indie',
      provider: 'youtube',
      youtubeVideoId: '_u_p_e68M8I',
    ),
  ];

  /// Returns all available built-in playlists.
  static List<Playlist> getBuiltinPlaylists() => List.unmodifiable(_builtinPlaylists);

  /// Returns the featured playlist for the Home screen banner.
  static Playlist getFeaturedPlaylist() => _builtinPlaylists.first;

  /// Retrieves a built-in playlist by its ID.
  static Playlist? getPlaylistById(String id) {
    try {
      return _builtinPlaylists.firstWhere((p) => p.id == id);
    } catch (_) {
      return null;
    }
  }
}
